site_name: flowpaths

nav:
  - Home: index.md
  - Minimum Flow Decomposition: minimumflowdecomposition.md
  - Abstract Path Model: abstractpathmodel.md
  - Solver Wrapper: solverwrapper.md

use_directory_urls: false

theme:
  name: material
  palette:
    primary: white
  features:
    - content.code.copy
  logo: flowpaths-logo.svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML


markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - smarty
  - mdx_math:
      add_preview: true
      enable_dollar_delimiter: true  # In order to activate math with $...$. Otherwise, math is rendered with \(...\)
  - pymdownx.details

plugins:
  - search 
  - macros:
      module_name: docs/getversion
  - mkdocstrings:
      default_handler: python
      