site_name: flowpaths

nav:
  - Home: 
    - About: index.md
    - References: references.md
  - Decomposition models:
    - Models:
      - Minimum Flow Decomposition: minimum-flow-decomposition.md
      - k-Flow Decomposition: k-flow-decomposition.md
      - k-Least Absolute Errors: k-least-absolute-errors.md
      - k-Minimum Path Error: k-min-path-error.md
    - Additional options:
      - Solver options and optimizations: solver-options-optimizations.md
      - Subpath constraints: subpath-constraints.md
      - Ignoring edges: ignoring-edges.md
      - Additional start/end nodes: additional-start-end-nodes.md
      - Optimization Routine for k: numpathsoptimization.md
      - Flows/weights on nodes: node-expanded-digraph.md
  - Developing new models:
    - Abstract Path Model: abstract-path-model.md
    - Solver Wrapper: solver-wrapper.md
    - stDiGraph: stdigraph.md  

use_directory_urls: false

theme:
  name: material
  palette:
    primary: white
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
  logo: flowpaths-logo.svg  

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - smarty
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details


plugins:
  - search 
  - macros:
      module_name: docs/getversion
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: false
            docstring_options:
            merge_init_into_class: true
            # docstring_section_style: spacy
            separate_signature: true
            show_signature_annotations: true
            # signature_crossrefs: true
            line_length: 60

      